author: billofbong
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.awesomecraft.plugins.tempop.TempOp
name: Temp Op
startup: postworld
version: '1.0'
commands:
  tempop:
    description: Temporarily ops someone
    usage: 